#!/usr/bin/env python 
""""
boxplot distribution of sxl transcript in female
"""



import sys
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

df_samples = pd.read_csv( sys.argv[1]) 
soi = df_samples["sex"] == "female"

df_gene = pd.DataFrame()
for sample in df_samples["sample"] [soi]:
        
        fname = os.path.join( sys.argv[2], sample, "t_data.ctab" ) #fname is filename, builds file path to sample
        df = pd.read_csv( fname, sep="\t" )
        roi = df ["gene_name"] == "Sxl"
        df_gene[sample] = df[roi]["FPKM"]
#print df_gene

        log_dfgene = np.log1p(df_gene)


plt.figure()
plt.boxplot( log_dfgene.values )
plt.savefig( "boxplot.png" )
plt.close() 
