#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()

count = 0
for i in lines:
    if i.startswith( "@"):
        continue
    fields = i.split("\t")
    if "NM:i:0" in i:
        count += 1
        
print count
    