#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()
count = 0
for i in lines:
    if i.startswith( "@" ):
        continue
    while count < 10:
        fields = i.split("\t")
        count += 1
        print fields[0] 