#!/usr/bin/env python

import sys

lines = sys.stdin.readlines()

sum = 0
for i in lines:
    if i.startswith( "@" ):
        continue
    fields = i.split("\t")
    if len(fields)<4: continue
    MAPQ = float(fields[4])
    sum += MAPQ
    
average_MAPQ = (sum / 22145900) 
    
print average_MAPQ
