#!/usr/bin/env python
"""
script to plot a scattered distribution of pca data from scer data
"""

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


pca = open(sys.argv[1])

pca1 = []
pca2 = []


for data in pca:
    fields = data.split()
    pca1.append(fields[2])
    pca2.append(fields[3])




plt.figure()
plt.scatter( pca1, pca2, alpha = 0.7, c = "green" )
plt.xlabel("PC1")              # label the x-axis
plt.ylabel("PC2")

plt.savefig("PCA_scatter.png")
plt.close()
