#!/usr/bin/env python

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

df = pd.read_cs( sys.argv[2], sep="\t")
coi = ["FPKM"]

fpkms = df[coi].values


def lin_fit(hist_bed):
    name_list = ['name', 'size', 'covered', 'mean0', 'mean']
    fpkm_df = pd.read_csv( sys.argv[2], sep='\t')
    hist_df = pd.read_csv( hist_bed, sep='\t', names=name_list )
    ['FPKM']
    ['mean']
    hist_list_c = sm.add_constant(hist_list)
    model = sm.OLS(fpkm_list, hist_list_c)
    results = model.fit()
    print results.summary()
lin_fit( sys.argv[1] )
















