#!/usr/bin/env python

import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

df = pd.read_csv( sys.argv[2], sep="\t" )

coi = ["FPKM"]

fpkm = []

for value in df[coi].values:
    fpkm.append(float(value))

f = open( sys.argv[1])
linear_regression_1 = []


for line in f:
    fields = line.rstrip("\r\n").split("\t")
    linear_regression_1.append(float(fields[5]))
    
x= linear_regression_1
y = fpkm
xc = sm.add_constant(x)



    
model = sm.OLS(linear_regression_1, fpkm)
results = model.fit()
print results.rsquared
print results.summary()

"""
plt.figure()
plt.scatter(linear_regression_1, fpkm, alpha= 0.4, c="green")
plt.title(str(sys.argv[1]))
plt.ylabel("mRNA abundance (FPKM)")
plt.xlabel("bigWigAVG")
plt.savefig( sys.argv[3] + ".png", bbox_inches="tight")

"""













