#!/usr/bin/env python

"""
Write a python script to compute the number of contigs, minimum/maximum/average contig length, and N50

"""

import sys
import fasta
import numpy as np
import matplotlib.pyplot as plt

fasta_file = open(sys.argv[1])

nuc_seq = []

for ident, sequence in fasta.FASTAReader(fasta_file):
    nuc_seq.append(sequence)

nuc_len = []

for i in range(len(nuc_seq)):
    nuc_len.append(len(nuc_seq[i]))

nuc_len.sort()
mean_nuc_len = np.mean(nuc_len)
    
print "Max = " + str(max(nuc_len))   
print "Min = " + str(min(nuc_len))   
print "Mean = " + str(mean_nuc_len)
contig_len = 0
for i in nuc_len:
    contig_len += i
    
print "L/2 = " + str(contig_len/2)
count = 0
for i in nuc_len:
    if count < contig_len/2:
        count += i
    else:
        print "N50 = " + str(i)
        break    
        
print len(nuc_len) 




#print mean_nuc_seq