#!/usr/bin/env python

import sys

f = sys.stdin

for row in f:
    if "DROME" not in row:
        continue
    if "FBgn" not in row:
        continue
    else:
        fields = row.split()
        print fields[-1], fields[-2]
        


            
            
 
      