#!/usr/bin/env python

import sys

identifier_map = {}
m = open(sys.argv[1])
for row in m:
    r = row.split(" ")
    f = r[0]
    a = r[1]
    identifier_map[f] = a

c_data = open(sys.argv[2])
argument = sys.argv[-1]
for row in c_data:
    r = row.split("\t")
    f = r[8]
    if "gene_id" in f:
       continue
    if argument == "-e":
        if f in identifier_map:
          print row, "\t", identifier_map[f]
        else:
          print "error in finding", f
    else:
        if f in identifier_map:
            print row, "\t", identifier_map[f]
    
    
         
          